export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOAD_USER_REQUEST: 'LOAD_USER_REQUEST',
    LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
    LOAD_USER_FAILURE: 'LOAD_USER_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    ALL_USERS_REQUEST: 'ALL_USERS_REQUEST',
    ALL_USERS_SUCCESS: 'ALL_USERS_SUCCESS',
    ALL_USERS_FAILURE: 'ALL_USERS_FAILURE',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',

    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',
    UPDATE_PASSWORD_RESET: 'UPDATE_PASSWORD_RESET',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',

    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_RESET: 'DELETE_USER_RESET',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

    CLEAR_ERRORS: 'CLEAR_ERRORS',
}