export const cartConstant = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
    SAVE_SHIPPING_INFO: "SAVE_SHIPPING_INFO",

    ADD_TO_SELL_CART: 'ADD_TO_SELL_CART',
    REMOVE_SELL_ITEM_CART: 'REMOVE_SELL_ITEM_CART',
    SAVE_SHIPPING_SELLER_INFO: "SAVE_SHIPPING_SELLER_INFO",

    CLEAR_ERRORS: 'CLEAR_ERRORS',
}