export const customerConstants = {
    ALL_CUSTOMER_REQUEST: 'ALL_CUSTOMER_REQUEST',
    ALL_CUSTOMER_SUCCESS: 'ALL_CUSTOMER_SUCCESS',
    ALL_CUSTOMER_FAILURE: 'ALL_CUSTOMER_FAILURE',

    CUSTOMER_DETAIL_REQUEST: 'CUSTOMER_DETAIL_REQUEST',
    CUSTOMER_DETAIL_SUCCESS: 'CUSTOMER_DETAIL_SUCCESS',
    CUSTOMER_DETAIL_FAILURE: 'CUSTOMER_DETAIL_FAILURE',

    NEW_CUSTOMER_REQUEST: 'NEW_CUSTOMER_REQUEST',
    NEW_CUSTOMER_SUCCESS: 'NEW_CUSTOMER_SUCCESS',
    NEW_CUSTOMER_RESET: 'NEW_CUSTOMER_RESET',
    NEW_CUSTOMER_FAILURE: 'NEW_CUSTOMER_FAILURE',

    DELETE_CUSTOMER_REQUEST: 'DELETE_CUSTOMER_REQUEST',
    DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
    DELETE_CUSTOMER_RESET: 'DELETE_CUSTOMER_RESET',
    DELETE_CUSTOMER_FAILURE: 'DELETE_CUSTOMER_FAILURE',

    UPDATE_CUSTOMER_REQUEST: 'UPDATE_CUSTOMER_REQUEST',
    UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
    UPDATE_CUSTOMER_RESET: 'UPDATE_CUSTOMER_RESET',
    UPDATE_CUSTOMER_FAILURE: 'UPDATE_CUSTOMER_FAILURE',
}

export const clearErrors = {
    CLEAR_ERRORS: 'CLEAR_ERRORS',
}