export const orderCosntants = {
    ALL_ORDERS_REQUEST: 'ALL_ORDERS_REQUEST',
    ALL_ORDERS_SUCCESS: 'ALL_ORDERS_SUCCESS',
    ALL_ORDERS_FAILURE: 'ALL_ORDERS_FAILURE',

    MY_ORDERS_REQUEST: 'MY_ORDERS_REQUEST',
    MY_ORDERS_SUCCESS: 'MY_ORDERS_SUCCESS',
    MY_ORDERS_FAILURE: 'MY_ORDERS_FAILURE',

    CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

    UPDATE_ORDER_REQUEST: 'UPDATE_ORDER_REQUEST',
    UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
    UPDATE_ORDER_RESET: 'UPDATE_ORDER_RESET',
    UPDATE_ORDER_FAILURE: 'UPDATE_ORDER_FAILURE',

    DELETE_ORDER_REQUEST: 'DELETE_ORDER_REQUEST',
    DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
    DELETE_ORDER_RESET: 'DELETE_ORDER_RESET',
    DELETE_ORDER_FAILURE: 'DELETE_ORDER_FAILURE',

    ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
    ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
    ORDER_DETAILS_FAILURE: "ORDER_DETAILS_FAILURE",

    CLEAR_ERRORS: 'CLEAR_ERRORS',
}
