export const productConstants = {
    ALL_PRODUCT_REQUEST: 'ALL_PRODUCT_REQUEST',
    ALL_PRODUCT_SUCCESS: 'ALL_PRODUCT_SUCCESS',
    ALL_PRODUCT_FAILURE: 'ALL_PRODUCT_FAILURE',

    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
    PRODUCT_DETAIL_FAILURE: 'PRODUCT_DETAIL_FAILURE',

    NEW_PRODUCT_REQUEST: 'NEW_PRODUCT_REQUEST',
    NEW_PRODUCT_SUCCESS: 'NEW_PRODUCT_SUCCESS',
    NEW_PRODUCT_FAILURE: 'NEW_PRODUCT_FAILURE',
    NEW_PRODUCT_RESET: 'NEW_PRODUCT_RESET',

    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
    DELETE_PRODUCT_RESET: 'DELETE_PRODUCT_RESET',

    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
    UPDATE_PRODUCT_RESET: 'UPDATE_PRODUCT_RESET',
}

export const clearErrors = {
    CLEAR_ERRORS: 'CLEAR_ERRORS',
}