export const sellConstant = {
    ALL_SELL_REQUEST: 'ALL_SELL_REQUEST',
    ALL_SELL_SUCCESS: 'ALL_SELL_SUCCESS',
    ALL_SELL_FAILURE: 'ALL_SELL_FAILURE',

    CREATE_SELL_REQUEST: 'CREATE_SELL_REQUEST',
    CREATE_SELL_SUCCESS: 'CREATE_SELL_SUCCESS',
    CREATE_SELL_FAILURE: 'CREATE_SELL_FAILURE',

    UPDATE_SELL_REQUEST: 'UPDATE_SELL_REQUEST',
    UPDATE_SELL_SUCCESS: 'UPDATE_SELL_SUCCESS',
    UPDATE_SELL_RESET: 'UPDATE_SELL_RESET',
    UPDATE_SELL_FAILURE: 'UPDATE_SELL_FAILURE',

    DELETE_SELL_REQUEST: 'DELETE_SELL_REQUEST',
    DELETE_SELL_SUCCESS: 'DELETE_SELL_SUCCESS',
    DELETE_SELL_RESET: 'DELETE_SELL_RESET',
    DELETE_SELL_FAILURE: 'DELETE_SELL_FAILURE',

    SELL_DETAILS_REQUEST: "SELL_DETAILS_REQUEST",
    SELL_DETAILS_SUCCESS: "SELL_DETAILS_SUCCESS",
    SELL_DETAILS_FAILURE: "SELL_DETAILS_FAILURE",

    CLEAR_ERRORS: 'CLEAR_ERRORS'
}