export const vendorConstants = {
    ALL_VENDOR_REQUEST: 'ALL_VENDOR_REQUEST',
    ALL_VENDOR_SUCCESS: 'ALL_VENDOR_SUCCESS',
    ALL_VENDOR_FAILURE: 'ALL_VENDOR_FAILURE',

    VENDOR_DETAIL_REQUEST: 'VENDOR_DETAIL_REQUEST',
    VENDOR_DETAIL_SUCCESS: 'VENDOR_DETAIL_SUCCESS',
    VENDOR_DETAIL_FAILURE: 'VENDOR_DETAIL_FAILURE',

    NEW_VENDOR_REQUEST: 'NEW_VENDOR_REQUEST',
    NEW_VENDOR_SUCCESS: 'NEW_VENDOR_SUCCESS',
    NEW_VENDOR_RESET: 'NEW_VENDOR_RESET',
    NEW_VENDOR_FAILURE: 'NEW_VENDOR_FAILURE',

    DELETE_VENDOR_REQUEST: 'DELETE_VENDOR_REQUEST',
    DELETE_VENDOR_SUCCESS: 'DELETE_VENDOR_SUCCESS',
    DELETE_VENDOR_RESET: 'DELETE_VENDOR_RESET',
    DELETE_VENDOR_FAILURE: 'DELETE_VENDOR_FAILURE',

    UPDATE_VENDOR_REQUEST: 'UPDATE_VENDOR_REQUEST',
    UPDATE_VENDOR_SUCCESS: 'UPDATE_VENDOR_SUCCESS',
    UPDATE_VENDOR_RESET: 'UPDATE_VENDOR_RESET',
    UPDATE_VENDOR_FAILURE: 'UPDATE_VENDOR_FAILURE',
}

export const clearErrors = {
    CLEAR_ERRORS: 'CLEAR_ERRORS',
}